### ISSUE TITLE
Dropdown search is blank sometimes

### ISSUE THREAD

**Issue by 4unkur** [intelliants/subrion-template-autosales#10]
![record_160401_115014](https://cloud.githubusercontent.com/assets/7892851/14198794/eb89c932-f7ff-11e5-8769-0323e18a9a40.gif)

**Comment by 4unkur** [comment]
Here's the report from our customer:

> 5 - the Popular makes area is not displayed sometimes when on other pages than Home, when you press the search for a car button and the drop down search appear the Popular makes area is empty. Try to show and hide the drop down search a couple of times without reloading the page. and the first time the drop down search is showed it goes all way down and then quickly resize to its normal height...

**Comment by glebovsky** [comment]
Block removed from inner pages.
